version: "3"

services:
  ufc-ripper:
    build: .
    image: wiknew1/ripper-test
    container_name: ufc-ripper
    restart: "no"
    volumes:
      - ./config:/ufcr/config # Configuration files
      - ~/Downloads/ufc-ripper:/downloads # Video downloads
    ports:
      - "8383:8383"
